### ISSUE TITLE
Group browser versions with no change

### ISSUE THREAD

**Issue by sidvishnoi** [sidvishnoi/respec-caniuse-route#8]
See https://github.com/w3c/respec/issues/3213 and https://github.com/w3c/manifest/issues/939#issuecomment-729076079

While creating HTML response (`createResponseBodyHTML`), if `Options.versions` is zero, group browser versions into one like caniuse does. This will ensure we show entire caniuse data, and not just last n versions.

It might make sense to do it even when `Options.versions` is not zero.

**Comment by marcoscaceres** [comment]
Grouping should probably just be the default. Then the dropdown can just group into the various support categories (same as caniuse does).

**Comment by sidvishnoi** [comment]
Moved to https://github.com/marcoscaceres/respec.org/issues/149
